server:
  port: 9041
  error:
    path: /error
    whitelabel:
      enabled: true
  servlet:
    context-path: /auth-realname-api
  tomcat:
    basedir: /auth/realname
    uri-encoding: UTF-8
    min-spare-threads: 10


spring:
  application:
    name: auth-realname-api

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xwk?useUnicode=true&characterEncoding=utf-8&connectTimeout=60000&socketTimeout=60000
    username: root
    password: hy190418
    driver-class-name: com.mysql.jdbc.Driver
    pool-size: 10
    maximum-pool-size: 3
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 3
      max-active: 10
      minIdle: 3
      max-wait: 60000
      use-unfair-lock: true
      validation-query: select 'x'
      validation-query-timeout: 10
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      pool-prepared-statements: false
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat,wall,slf4j
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: false
            drop-table-allow: false
            log-violation: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: false
        session-stat-max-count: 1000
        profile-enable: true
      stat-view-servlet: # StatViewServlet配置，http://127.0.0.1:8080/mini-web/druid/index.html
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: zhaoj
        login-password: zhaoj
      aop-patterns: com.auth.realname.mapper.*
  redis:
    database: 0 #索引（默认为0）
    host: 127.0.0.1 #地址
    port: 6379 #端口号
    #password:  #连接密码（默认空）
    timeout: 6000
    pool:
      max-idle: 8 #连接池中的最大空闲连接
      min-idle: 0 #连接池中的最小空闲连接
      max-active: 8 #连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）

mybatis:
  type-aliases-package: com.auth.realname.bean
  type-handlers-package: com.auth.realname.mapper
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: PARTIAL
    default-statement-timeout: 30
    default-fetch-size: 100
    local-cache-scope: STATEMENT
    jdbc-type-for-null: NULL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  config: classpath:logback.xml
  level:
    root: INFO
    org.springframework.web: INFO
    tk.mybatis.pagehelper.mapper: TRACE

