redis:
  lock-timeout-seconds: 30
  try-lock-wait-seconds: 10

spring:
  redis:
    database: 0 #索引（默认为0）
    host: 127.0.0.1 #地址
    port: 6379 #端口号
    #password:  #连接密码（默认空）
    timeout: 6000
    pool:
      max-idle: 8 #连接池中的最大空闲连接
      min-idle: 0 #连接池中的最小空闲连接
      max-active: 8 #连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）